In [21]:
import numpy as np
import matplotlib
import scipy

x=np.random.rand(100,1)
y=5*x*x+0.1*np.random.randn(100,1)
print(x)
print(y)

[[ 0.05520108]
 [ 0.05565295]
 [ 0.85170905]
 [ 0.14091818]
 [ 0.20211826]
 [ 0.59099533]
 [ 0.43644876]
 [ 0.0366806 ]
 [ 0.21870368]
 [ 0.56524423]
 [ 0.33263677]
 [ 0.74911531]
 [ 0.99655838]
 [ 0.66186213]
 [ 0.02922166]
 [ 0.18357949]
 [ 0.50411179]
 [ 0.82039429]
 [ 0.88844925]
 [ 0.97344613]
 [ 0.77829723]
 [ 0.9373091 ]
 [ 0.1206322 ]
 [ 0.87431935]
 [ 0.46370846]
 [ 0.53136978]
 [ 0.48738602]
 [ 0.70154764]
 [ 0.68198041]
 [ 0.91012838]
 [ 0.89025189]
 [ 0.93529321]
 [ 0.50755149]
 [ 0.02081709]
 [ 0.42821496]
 [ 0.47921894]
 [ 0.53245852]
 [ 0.69502543]
 [ 0.21824152]
 [ 0.93385251]
 [ 0.13915147]
 [ 0.16203349]
 [ 0.22661918]
 [ 0.35757304]
 [ 0.86236072]
 [ 0.02975674]
 [ 0.36438737]
 [ 0.5063943 ]
 [ 0.93293831]
 [ 0.13243864]
 [ 0.72685758]
 [ 0.88050481]
 [ 0.64756119]
 [ 0.84880908]
 [ 0.50939278]
 [ 0.29429715]
 [ 0.32576604]
 [ 0.02844896]
 [ 0.67750632]
 [ 0.02327099]
 [ 0.80989912]
 [ 0.0996947 ]
 [ 0.78874865]
 [ 0.01888802]
 [ 0.32290565]
 [ 0.46060492]
 [ 0.27875

In [28]:
a=[1]*100
print(a)
a=np.asarray(a)
print(a)
np.set_printoptions(threshold=np.nan)


[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [31]:
x2=np.empty([100,1])
print (x2)
for i in range(100):
    x2[i]=x[i]*x[i]
print (x2)
print(x[2]*x[2])

[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]
[[  3.04715952e-03]
 [  3.09725049e-03]
 [  7.25408312e-01]
 [  1.98579346e-02]
 [  4.08517914e-02]
 [  3.49275484e-01]
 [  1.90487519e-01]
 [  1.34546652e-03]
 [  4.78312987e-02]
 [  3.19501040e-01]
 [  1.10647223e-01]
 [  5.61173742e-01]
 [  9.93128608e-01]
 [  4.38061480e-01]
 [  8.53905439e-04]

In [36]:
X=np.empty([3,100])
for i in range(100):
    X[0,i]=1
    X[1,i]=x[i]
    X[2,i]=x[i]*x[i]

print(X)

[[  1.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00  